name: Build and Pack
on:
  pull_request:
    branches:
      - master
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push app
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: xmile/scgame:latest

      - name: Build and push api
        uses: docker/build-push-action@v5
        with:
          context: ./wss
          file: ./wss/Dockerfile
          push: true
          tags: xmile/scgame-api:latest
